---
- name: create cloudformation stack network
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: present
    region: "{{ aws_region }}"
    disable_rollback: false
    template: roles/create_network/cloudformation/network.yaml
    template_parameters:
      EnvName: "{{ EnvName }}"
      vpcCidr: "{{ vpcCidr }}"
      pubSubnet1: "{{ pubSubnet1 }}"
      pubSubnet2: "{{ pubSubnet2 }}"
      privSubnet1: "{{ privSubnet1 }}"
      privSubnet2: "{{ privSubnet2 }}"

- name: set cloudformation facts
  cloudformation_info:
    stack_name: "{{ stack_name }}"
  register: my_stack

- debug:
    msg: "{{ my_stack.cloudformation[stack_name].stack_outputs }}"