---
- name: create cloudformation stack network
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: present
    region: "{{ aws_region }}"
    disable_rollback: false
    template: network.yaml
    template_parameters:
      EnvName: "{{ envName }}"
      vpcCidr: "{{ vpcCidr }}"
      pubSubnet1: "{{ pubSubnet1 }}"
      pubSubnet2: "{{ pubSubnet2 }}"
      privSubnet1: "{{ privSubnet1 }}"
      privSubnet2: "{{ privSubnet2 }}"