---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-python
  template:
    metadata:
      labels:
        app: myapp-python
    spec:
      containers:
      - name: myapp-python
        image: 10.247.101.47:5000/kshanuanand/myapp:1.7
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-python-service
spec:
  type: NodePort
  selector:
    app: myapp-python
  ports:
    - nodePort: 30000
      port: 5000
      targetPort: 5000
