- set_fact:
    stack_name1: "{{ stack_name }}"

- name: set cloudformation facts
  cloudformation_facts:
    stack_name: "{{ stack_name }}"
  register: my_stack_ec2

- debug:
    msg: "{{ my_stack_ec2.ansible_facts.cloudformation[stack_name1].stack_outputs }}"

- set_fact:
    k8s_master: "{{ my_stack_ec2.ansible_facts.cloudformation[stack_name1].stack_outputs['Ec2IPPUB'] }}"

- debug:
    msg: "{{ k8s_master }}"

- name: create inventory file for post config
  template:
    src: k8shosts.ini.j2
    dest: group_vars/all/k8shosts.ini

- name: Wait for kubeadm to complete and k8s cluster to start
  action: uri url=https://{{ k8s_master }}:6443/livez?verbose validate_certs=False
  register: result
  until: result.msg.find('OK') != -1
  retries: 18
  delay: 10

- name: K8s health check result
  debug:
    msg: "{{ result.status }} {{ result.msg }}"