- name: Copy deployment file to target hosts
  template:
    src: mydeployment.yaml.j2
    dest: /home/ubuntu/mydeployment.yaml

- name: delete deployment of already present
  shell: |
    kubecl delete deployment myapp
    kubectl delete svc myapp-python-service

- name: install the deployment again
  shell: |
    kubectl apply -f /home/ubuntu/mydeployment.yaml

