- name: Copy deployment file to target hosts
  template:
    src: mydeployment.yaml.j2
    dest: /home/ubuntu/mydeployment.yaml

- name: delete deployment of already present
  shell: |
    depCnt=$(kubectl get deployments | grep myapp | wc -l)
    if [ $depCnt -gt 0 ]
    then
      kubectl delete deployment myapp
    fi
    svcCnt=$(kubectl get svc | grep myapp-python-service| wc -l)
    if [ $svcCnt -gt 0 ]
    then
      kubectl delete svc myapp-python-service
    fi

- name: install the deployment again
  shell: |
    kubectl apply -f /home/ubuntu/mydeployment.yaml

- name: Wait for application to start
  action: uri url=http://localhost:30000/ validate_certs=False
  register: result
  until: result.msg.find('My name is myapp') != -1
  retries: 18
  delay: 10