- name: K8s health check result
  debug:
    msg: "{{ result.status }} {{ result.msg }}"

- name: Task to create .kube in ubuntu user
  file:
    path: /home/ubuntu/.kube
    owner: ubuntu
    group: ubuntu
    state: directory

- name: Copy kubeconfig in ubuntu user
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    owner: ubuntu
    group: ubuntu