---
- name: Create EC2 instance for deployment
  hosts: all
  vars:
    ansible_host_key_checking: False
    ansible_ssh_host_key_checking: False
    ansible_paramiko_host_key_checking: False
    host_key_checking: False
    ssh_host_key_checking: False
    paramiko_host_key_checking: False
  roles:
    - create_ec2