Description: >
  Cloudformation to create an EC2 instance. It will install docker and rke binary along with.

Parameters:
  EnvName:
    Type: String
    Description: Name of the EC2 created

  VPCEnvName:
    Type: String
    Description: Stack Name of VPC Network

  EC2AmiId:
    Type: String
    Description: AMI Id for Ec2 Instance

  EC2Key:
    Type: String
    Description: Name of the Key to be used to login into EC2 instance
  
  EC2Instance:
    Type: String
    Description: EC2 instance type t obe used
    Default: t2.micro

Resources:

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Aloow http and ssh to host
      VpcId:
        Fn::ImportValue:
          !Sub "${VPCEnvName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 30000
        ToPort: 30100
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 6443
        ToPort: 6443
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 2379
        ToPort: 2380
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 10250
        ToPort: 10252
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0

  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref EC2AmiId
      KeyName: !Ref EC2Key
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - Ref: EC2SecurityGroup
          SubnetId:
            Fn::ImportValue:
              !Sub "${VPCEnvName}-PUB1-SubNet"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -x
          # Install docker
          apt-get update
          apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          add-apt-repository \
          "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) \
          stable"
          apt-get update
          apt-get install -y docker-ce
          usermod -aG docker ubuntu
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
          deb https://apt.kubernetes.io/ kubernetes-xenial main
          EOF
          sudo apt-get update
          sudo apt-get install -y kubelet kubeadm kubectl
          sudo apt-mark hold kubelet kubeadm kubectl
          cd /root/
          kubeadm init
      InstanceType: !Ref EC2Instance
      BlockDeviceMappings:
      - DeviceName: "/dev/sdk"
        Ebs:
          VolumeSize: '10'

Outputs:
  Ec2IP-PUB:
    Description: Public IP of the EC2 instance created
    Value: !GetAtt MyEC2.PublicDnsName
    Export:
      Name: !Sub ${EnvName}-PUB-EC2
  Ec2IP-PRIV:
    Description: Private IP of the EC2 instance created
    Value: !GetAtt MyEC2.PrivateDnsName
    Export:
      Name: !Sub $P{EnvName}-PRIV-EC2
